# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 80
  servlet:
    context-path: /thank-spring
# 配置之后可以在页面上使用 ${request.contextPath}


spring:
  profiles:
    active: prod
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  freemarker:
      suffix: .html
      request-context-attribute: request
  # RabbitMQ消息队列
  rabbitmq:
    host: 192.168.0.132
    username: guest
    password: guest
    port: 5672
  # 全文检索ES
  elasticsearch:
    jest:
      uris: http://192.168.0.132:9200
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 192.168.0.132:9300
mybatis:
  type-aliases-package: top.wycfight.thankspring.mybaits.*
  configuration:
    map-underscore-to-camel-case: true
    # 打印sql, 方便调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
    default-statement-timeout: 60
    default-fetch-size: 100

# Swagger界面内容配置
swagger:
  title: Thank API接口文档
  description: good good study, day day up!
  version: 1.0.0
  termsOfServiceUrl: http://wycfight.top
  contact:
    name: ASpring
    url: http://wycfight.top
    email: wycfight@163.com


# 配置redis和shiro 缓存是否开启
thank:
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
  shiro:
    redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】


# 极验验证码的ID和KEY
#ID 002bc30ff1eef93e912f45814945e752
#KEY 4193a0e3247b82a26f563d595c447b1a
geetest:
  geetest_id: 48a6ebac4ebc6642d68c217fca33eb4d
  geetest_key: 4f1c085290bec5afdc54df73535fc361
  newfailback: false