# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 80
  servlet:
    context-path: /thank-spring
# 配置之后可以在页面上使用 ${request.contextPath}


spring:
  profiles:
    active: prod
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  freemarker:
      suffix: .html
      request-context-attribute: request
mybatis:
  type-aliases-package: top.wycfight.thankspring.mybaits.*
  configuration:
    map-underscore-to-camel-case: true
    # 打印sql, 方便调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
    default-statement-timeout: 60
    default-fetch-size: 100

# Swagger界面内容配置
swagger:
  title: Thank API接口文档
  description: good good study, day day up!
  version: 1.0.0
  termsOfServiceUrl: http://wycfight.top
  contact:
    name: ASpring
    url: http://wycfight.top
    email: wycfight@163.com

# Login页面一些参数
login:
  title: 随便做做啊

# 配置redis和shiro 缓存是否开启
thank:
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
  shiro:
    redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】
