# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 80
  servlet:
    context-path: /thank-spring
# 配置之后可以在页面上使用 ${request.contextPath}


spring:
  profiles:
    active: prod
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  freemarker:
      suffix: .html
      request-context-attribute: request
  # RabbitMQ消息队列
  rabbitmq:
    host: 192.168.0.132
    username: guest
    password: guest
    port: 5672
  # 全文检索ES
  elasticsearch:
    jest:
      uris: http://192.168.0.132:9200
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 192.168.0.132:9300

# Swagger界面内容配置
swagger:
  title: Thank API接口文档
  description: good good study, day day up!
  version: 1.0.0
  termsOfServiceUrl: http://wycfight.top
  contact:
    name: ASpring
    url: http://wycfight.top
    email: wycfight@163.com


# 配置redis和shiro 缓存是否开启
thank:
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
  shiro:
    redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】


# 极验验证码的ID和KEY
#ID 002bc30ff1eef93e912f45814945e752      48a6ebac4ebc6642d68c217fca33eb4d
#KEY 4193a0e3247b82a26f563d595c447b1a     4f1c085290bec5afdc54df73535fc361
geetest:
  geetest_id: 002bc30ff1eef93e912f45814945e752
  geetest_key: 4193a0e3247b82a26f563d595c447b1a
  newfailback: true



# mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  # 实体扫描，多个Package用逗号或者分号分隔
  type-aliases-package: top.wycfight.thankspring.modules.*.bean
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true